### ISSUE TITLE
How i can contact you ?

### ISSUE THREAD

**Issue by MyNewBie** [sirius1242/sirius1242.github.io#1]
Hi, sorry i used issue of this repo for contact with you , is there any way to contact you email/discord/...?

**Comment by sirius1242** [comment]
Emmmm, I think you can just find my email in my GitHub account profile. Or
you can just reply to this email.

MyNewBie <notifications@github.com> 于2020年8月22日周六 下午11:03写道：

**Comment by MyNewBie** [comment]
Hi, my request is about your teeworlds ball repo , i wanted make issue but seems its closed by you , so here :The "TILE_GOAL_TEAM_1" m_Height and m_Width must be half of tee size character like old teeball mod or GreYFox football mod https://github.com/unique-clan/football/blob/teefoot/src/game/collision.cpp#L228 and https://github.com/unique-clan/football/blob/teefoot/src/game/collision.cpp#L57 im not sure thats the fix.Take a look at pic you can understand better what i mean sorry for my english bad.

**Comment by MyNewBie** [comment]
![tabletennisfix](https://user-images.githubusercontent.com/3491065/90960487-26d71780-e4b7-11ea-90a3-d50628e39250.png)

**Comment by sirius1242** [comment]
Emmmm, sorry, this version is written before I known teefoot, just because I didn't find proper ball mod in GitHub, and we want to play basketball. So I didn't notice the problem about table tennis. I will check it recently.

**Comment by sirius1242** [comment]
The reason why you can't make an issue for that ball repo may because that repo is the forked version.

**Comment by MyNewBie** [comment]
> Emmmm, sorry, this version is written before I known teefoot, just because I didn't find proper ball mod in GitHub, and we want to play basketball. So I didn't notice the problem about table tennis. I will check it recently.

Thank you , would be great.

> The reason why you can't make an issue for that ball repo may because that repo is the forked version.

Didnt know that. Thanks

**Comment by sirius1242** [comment]
I didn't clearly understand your description, so I just update the GetTIle() function according to https://github.com/unique-clan/football/blob/teefoot/src/game/collision.cpp#L228, I don't know if this solved the problem.

**Comment by MyNewBie** [comment]
> I didn't clearly understand your description, so I just update the GetTIle() function according to https://github.com/unique-clan/football/blob/teefoot/src/game/collision.cpp#L228, I don't know if this solved the problem.

Its about in tabletennis ,on the goal tile when you want get back the ball you cant caz ball touch the tile and its gone to own goal but in old ball mods in tabletennis when you on the goal tile you can get the ball becaz goal happen when ball touch the half of goal tile.

**Comment by sirius1242** [comment]
[This version](https://github.com/TeeworldsCN/teeworlds-teefoot ) may fit your requirement?  And version in https://github.com/sirius1242/teeworlds-ball may not maintain any more.
