### ISSUE TITLE
Where the hell have you been

### ISSUE THREAD

**Issue by ghost** [sirius1242/sirius1242.github.io#2]
You little Sirius,
We haven't seen you for quite a long time in any teeworlds related group, we guys are wondering where the hell have you been?

Well, I guess I've known the answer:

 __*You must be dating your girlfriend, ah??*__

So are your fingers sufficient to count the number now? haha
(one hand, two hands....555 .jpg)

**Comment by sirius1242** [comment]
I think this is abuse, closed.
